### PR TITLE
Update ERP URL

### PR DESCRIPTION
**Pull request by TheMousePotato**

### CODE REVIEW

**Comment by icyflame** [comment]
@TheMousePotato Have you tested this?

**Comment by TheMousePotato** [comment]
No @icyflame.

**Comment by icyflame** [comment]
Okay, please test and report back in that case. :)

**Comment by TheMousePotato** [comment]
It's fetching the security question correctly from ERP. But after that, it's showing one of the errors in the log attached.

`python3 gyft.py --user 17NA30013
kpython3\Enter your ERP password: 
father's name
Enter the answer to the security question: 
Traceback (most recent call last):
  File "gyft.py", line 99, in <module>
    txt = tds[a].find('b').text.strip()
AttributeError: 'NoneType' object has no attribute 'text'
 potato@mousebox  ~/Desktop/MetaKGP/gyft   potato-patch  python3 gyft.py --user 17NA30013
kpython3\Enter your ERP password: 
father's name
Enter the answer to the security question: 
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/usr/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.6/dist-packages/urllib3/util/retry.py", line 357, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.6/dist-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/usr/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "gyft.py", line 46, in <module>
    headers = headers)
  File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 555, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/adapters.py", line 490, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',)) potato@mousebox  ~/Desktop/MetaKGP/gyft   potato-patch  python3 gyft.py --user 17NA30013
kpython3\Enter your ERP password: 
father's name
Enter the answer to the security question: 
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunk`

**Comment by nishnik** [comment]
I think it's because there's no time table right now. Let's wait patiently.

**Comment by icyflame** [comment]
Yeah, my timetable looks like this too. We can merge this in right after we test it a few times. 
image

**Comment by nishnik** [comment]
+1 from me.

**Comment by nishnik** [comment]
Thanks @TheMousePotato.

**Comment by nishnik** [comment]
And also, thanks @icyflame for always being the first one to reply. :1st_place_medal:

**Pull request merged**
