### PR TITLE
Add key check before attempting to access event['summary'] and fix code style issues

### LINKED ISSUE #17: del_events.py giving key error
```
if ("Class of " in event['summary'] or "Lab of " in event['summary']):
```

KeyError: 'summary'

### PR DESCRIPTION
**Pull request by Shankusu993**
Attempts to fix #17  
adds a key check `if "summary" in event ...`, so they key "summary" is not accessed if it's not available and hence solving the issue.
Also, improve code style following the pep8 guideline.

### CODE REVIEW

**Comment by icyflame** [comment]
@Shankusu993 Did you test this locally to ensure that only the events which match the Gyft regex are deleted? If so, we can merge this PR.

**Comment by thealphadollar** [comment]
@Shankusu993 @icyflame Updates?

**Comment by icyflame** [comment]
@thealphadollar I want to ensure that someone ran this code locally and tested that the ICS files were created properly before merging. :red_circle:

**Comment by thealphadollar** [comment]
@icyflame Please tell me a method to test it, I'll test it.

**Comment by icyflame** [comment]
@thealphadollar You have to run the command to add the events to a Google Calendar, and then run the `del_events` script. These conditions should be met:

- [ ] Script runs without throwing an error
- [ ] Script deletes events from the Google Calendar
- [ ] Script deletes only those events from Calendar which were created by Gyft

**Pull request closed without merging**
