### PR TITLE
Added Notifications

### PR DESCRIPTION
**Pull request by Harshbansal8705**
Added a feature of notification 3 hours, 1 hour and 20 minutes before classes.

### CODE REVIEW

**Review by proffapt — COMMENTED** [review]
Why to add them specifically? Isn't it bydefualt?
I receive calendar notifications on my phone and pc (Pc needs to allow notifs as any other website)

**Comment by Harshbansal8705** [comment]
The default notification is set to 10 minutes before the class, which may not be useful sometimes if the person is in the room. So, I have added the notifications for 3 hours, 1 hour and 10 minutes before the class.

**Comment by Devansh-bit** [comment]
I get notification 30 minutes before class

**Comment by proffapt** [comment]
> I have added the notifications for 3 hours, 1 hour and 10 minutes before the class.

Not practically feasible for the following since we will get multiple notifications probably around the same time. Currently it's just one class which is about to happen.

**Comment by ashwinpra** [comment]
Like mentioned above by Devansh, I get notifications 30 minutes before the class, which I feel is sufficient. 
Also like Arpit said, getting notifications 3 hrs or 1 hr before the class could clash with the notification for another class, so I don't think we should add them. 
Good work though, appreciate the effort for contribution :)

**Pull request closed without merging**
