### PR TITLE
feat: Events in Nalanda point to the exact classroom building.

### PR DESCRIPTION
**Pull request by Devansh-bit**

### CODE REVIEW

**Review by proffapt — COMMENTED** [review]
So, have you solved the issue, in which it shows coordinates in location section of calendar entry instead of the name?

**Comment by Devansh-bit** [comment]
I do not think it is possible to have both location name and coordinates in the location section of the event (It also doesn't make sense to do that for any general application that is not this specific scenario tbh). Although to make it cleaner, we can use `plus codes` or `open location codes` which should make it look something like the attached screenshot. 
image

**Comment by Devansh-bit** [comment]
Changes incorporated in #112

**Comment by proffapt** [comment]
This is not how things are done..

One specific change must have a PR, now it will be hell to review..

**Comment by Devansh-bit** [comment]
I did that to prevent super hard to resolve merge conflicts from happening, because the codebase has been completely shuffled in #112 so it would have to be force committed either way. 

The changes are super easy to review in #112, as they've been implemented in a single place. I've already added a review request at the implementation and the changes can we reverted in less than 5 seconds if the changes are not acceptable.

**Comment by proffapt** [comment]
> I did that to prevent super hard to resolve merge conflicts

They are bound to happen when a big team works.

Anyways, will see how things work out.

**Pull request closed without merging**
