### PR TITLE
updated requests & fixed error for oauth2client in add_events.py

### PR DESCRIPTION
**Pull request by icskzmrinal**
Updated Requests requirement in requirements.txt. issue #46 created by @thealphadollar

### CODE REVIEW

**Comment by thealphadollar** [comment]
Why are there changes in files except requirements.txt

**Comment by thealphadollar** [comment]
Okay. That is great.

Can you please create an issue explaining it as well? And then reference it
in this PR in a comment.

**Comment by icskzmrinal** [comment]
Traceback (most recent call last):
  File "add_events.py", line 138, in <module>
    main()
  File "add_events.py", line 77, in main
    credentials = get_credentials()
  File "add_events.py", line 48, in get_credentials
    store = oauth2client.file.Storage(credential_path)
AttributeError: module 'oauth2client' has no attribute 'file'
These are the recent calls while running add_events.py

**Comment by thealphadollar** [comment]
Oh! I know that is an error but I mean to ask how does your change fix it. Well, the error occurs whenever you use `oauth2client.file` so once you have imported file you should replace all instances of `oauth2client.file` with just `file`.

**Comment by icskzmrinal** [comment]
oh right! I have corrected it and am updating as next commit. Should I create it as issue and mention here?

**Comment by icskzmrinal** [comment]
Corrected it for del_events.py. I think both Issue #47 and #49 are resolved

**Pull request merged**
