### PR TITLE
Updating subject codes for Industrial and Systems Engineering in autumn semester 2022-2023

### PR DESCRIPTION
**Pull request by proffapt**
- Adding "Introduction to basic manufacturing process lab" as course
- Updating course name and code for engineering economy as a course.
- Updating codes for various codes(as the curriculum was updated).

### CODE REVIEW

**Review by thealphadollar — COMMENTED** [review]
Hey Arpit, thanks for the pull request. 

Can you please attach a proof of the curriculum changes? It'll be helpful to verify.

**Comment by proffapt** [comment]
> Hey Arpit, thanks for the pull request.
> 
> Can you please attach a proof of the curriculum changes? It'll be helpful to verify.

image
will it suffice?

**Review by thealphadollar — APPROVED** [review]
Thanks Arpit for the continuous contributions 🙇🏽

**Comment by proffapt** [comment]
> Thanks Arpit for the continuous contributions 🙇🏽

Trying to be on your path, just a beginning (〜￣▽￣)〜

**Pull request merged**
