### PR TITLE
Fixed issue #100

### PR DESCRIPTION
**Pull request by shikharsoni07**
I converted `rows` to a string, replaced "CS10001" with "CS10003", then converted it back to BeautifulSoup.

Works without any errors.

### CODE REVIEW

**Comment by ashwinpra** [comment]
Looks good to me, great work :)

**Review by proffapt — CHANGES_REQUESTED** [review]
- Creating a separate loop just to do this, is a bit overhead. Can rather do this thing in the first line after or inside this loop https://github.com/metakgp/gyft/blob/5d59d63d3b3304553a22ed9f7ae6d53e2a337a83/gyft.py#L94 
- Look for some better way of doing this, i.e., without converting to string then to bs content, can't we do it directly when in bs content?

**Comment by shikharsoni07** [comment]
@proffapt 
I changed it such that just before looking up the subject names from subject codes, it looks for a match for "CS10001" and replaces with "CS10003". 

I think this is better than searching the whole bs content or dict for "CS10001" and then replacing it.

**Comment by proffapt** [comment]
> @proffapt I changed it such that just before looking up the subject names from subject codes, it looks for a match for "CS10001" and replaces with "CS10003".
> 
> I think this is better than searching the whole bs content or dict for "CS10001" and then replacing it.

Looks good to me. Just a clarification, have you tested it?

**Review by proffapt — COMMENTED** [review]
Looks good to me. 
Just a clarification, have you tested it?

**Comment by shikharsoni07** [comment]
Thank you so much!

**Pull request merged**
