### PR TITLE
fixed some bugs with scraping

### PR DESCRIPTION
**Pull request by ashwinpra**
- The scraping URL had to be given a semester number argument too, which I did not realise
- Also there was a bug in the code for calculating semester no. :/

### CODE REVIEW

**Review by proffapt — CHANGES_REQUESTED** [review]
remove `utils/.session` commit, add this file to `.gitignore`.. prefer using something like `.*session` if they may ignore every kind of session file

**Comment by ashwinpra** [comment]
Oh missed that, will remove it

**Comment by ashwinpra** [comment]
Just confirm that the regex is fine, I'm not so good at it lol

**Review by proffapt — APPROVED** [review]
LGTM

**Pull request merged**
