### PR TITLE
Update dates.py - Spring 21-22

### PR DESCRIPTION
**Pull request by thehorizondweller**
Update 4 reference dates for Spring 21-22

### CODE REVIEW

**Review by thealphadollar — APPROVED** [review]
Thank you for the changes Kshitij. Everything looks good to me.

PS. It is always a good idea to include references in the PR description. For instance, http://www.iitkgp.ac.in/files/acad_cal2122_2.pdf

**Comment by thealphadollar** [comment]
Would you mind updating the dates in gyft-serve as well?

https://github.com/metakgp/gyft-serve

**Comment by thealphadollar** [comment]
@sahil-shubham Can we please release a post on Metakgp Facebook page thanking Kshitij Anand?

**Comment by thehorizondweller** [comment]
I will keep in mind to include the references for future PRs. 
I will update it in gyft/serve as well if it hasn't been.

**Pull request merged**
