### PR TITLE
.ics file now shows full locations using full_locations.json

### PR DESCRIPTION
**Pull request by shikharsoni07**
tested:
image

### CODE REVIEW

**Comment by ashwinpra** [comment]
- In the case of Chemistry and Advanced Calculus for example, rather than adding `NC121, NC122` to the `full_location.json`, try to make it such that it searches for both entries (searching for one should also be fine I guess, as usually in such cases, the rooms would be close to each other) and gives their common location
- Have you tried adding the lat-long data of each location as well?


Also, unrelated to this PR specifically, but I would suggest you to create different branches on your fork for different issues next time, would make the PR more clean

**Comment by shikharsoni07** [comment]
> * In the case of Chemistry and Advanced Calculus for example, rather than adding `NC121, NC122` to the `full_location.json`, try to make it such that it searches for both entries (searching for one should also be fine I guess, as usually in such cases, the rooms would be close to each other) and gives their common location
> * Have you tried adding the lat-long data of each location as well?
> 
> Also, unrelated to this PR specifically, but I would suggest you to create different branches on your fork for different issues next time, would make the PR more clean

- I will make it such that it searches for the first room no. and adds that to the event. That should be sufficient I think.
- lat-long implementation wont be possible as far as I can say

**Comment by shikharsoni07** [comment]
I am new to git/github so sorry about that.
for some reason, my fork shows this:
image

Yesterday I made a PR and then it was merged with the main but it still shows my fork is ahead(it should only show those commits ahead which are yet to be merged right?). Dont know whats up 🙁

**Comment by proffapt** [comment]
> I am new to git/github so sorry about that. for some reason, my fork shows this: image
> 
> Yesterday I made a PR and then it was merged with the main but it still shows my fork is ahead(it should only show those commits ahead which are yet to be merged right?). Dont know whats up 🙁

prefer slack for such things.

**Comment by shikharsoni07** [comment]
>- In the case of Chemistry and Advanced Calculus for example, rather than adding NC121, NC122 to the full_location.json, try to make it such that it searches for both entries (searching for one should also be fine I guess, as usually in such cases, the rooms would be close to each other) and gives their common location

I can't think of any good way to do this.

I was thinking the structure of `full_location.json` could be made better. Its just room numbers as keys and full locations as an item under them. If we make it like building name as keys and all the room numbers in that building as items, maybe that would be better.

**Comment by proffapt** [comment]
It's gone for good

https://github.com/metakgp/gyft/compare/c1e16b2d56ef5ef7ce94d0d78b987cdf40687dfa..84b3dc5c1dc8ed3077cb9a2be177fbc34797834e

Make these changes and create a new PR

**Comment by proffapt** [comment]
test

**Pull request closed without merging**
